name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Debug working directory
        run: pwd
      - name: Debug tasks.json path
        run: node -e "const path = require('path'); console.log(path.join(process.cwd(), 'src/tasks.json'))"
      - name: Check tasks.json exists
        run: ls src/tasks.json
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: --experimental-vm-modules