name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: todo-cli/package.json

      - name: Install dependencies
        run: npm ci

      - name: Debug working directory
        run: pwd

      - name: Debug tasks.json path
        run: ls -la src/

      - name: Run tests
        run: npm test
        