name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Matches your local Node.js version (22.14.0)
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test